# /home/lrh/projects/gem5/src/protocol_converter/SConscript

Import('*')

SimObject('phy_abstraction/SimpleChipletLink.py', sim_objects=['SimpleChipletLink'])
SimObject('packet/PacketGenerator.py', sim_objects=['PacketGenerator'])
SimObject('link_layer/LinkLayer.py', sim_objects=['LinkLayer'])
#SimObject('converters/PCIeConverter.py', sim_objects=['PCIeConverter'])
SimObject('converters/ProtocolConverter.py', sim_objects=['ProtocolConverter'])

Source('phy_abstraction/SimpleChipletLink.cc')
Source('packet/PacketGenerator.cc')
Source('link_layer/LinkLayer.cc')
#Source('converters/PCIeConverter.cc')
Source('converters/ProtocolConverter.cc')

#DebugFlag('PCIeConverter')
DebugFlag('ProtocolConverter')
DebugFlag('LinkLayer')
DebugFlag('SimpleChipletLink')
DebugFlag('PacketGenerator')
