# /home/lrh/projects/gem5/src/protocol_converter/SConscript

Import('*')

SimObject('phy_abstraction/SimpleChipletLink.py', sim_objects=['SimpleChipletLink'])
SimObject('packet/PacketGenerator.py', sim_objects=['PacketGenerator'])
#SimObject('link_layer/PCIeLinkLayer.py', sim_objects=['PCIeLinkLayer'])
#SimObject('converters/PCIeConverter.py', sim_objects=['PCIeConverter'])
#SimObject('converters/ProtocolConverter.py', sim_objects=['ProtocolConverter'])

Source('phy_abstraction/SimpleChipletLink.cc')
Source('packet/PacketGenerator.cc')
#Source('link_layer/PCIeLinkLayer.cc')
#Source('converters/PCIeConverter.cc')
#Source('converters/ProtocolConverter.cc')
#Source('converters/TLPInterface.cc')

#DebugFlag('PCIeConverter')
#DebugFlag('ProtocolConverter')
#DebugFlag('PCIeLinkLayer')
DebugFlag('SimpleChipletLink')
DebugFlag('PacketGenerator')
#DebugFlag('TLPInterface')
