######################################################################
#
# File name : tb_crc16_compile.do
# Created on: Thu Apr 18 20:56:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../CRC.srcs/sources_1/new/crc16.v" \
"../../../../CRC.srcs/sim_1/new/tb_crc16.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

