######################################################################
#
# File name : tb_crc_wave.do
# Created on: Sat Jun 22 17:26:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
