######################################################################
#
# File name : tb_crc_simulate.do
# Created on: Sat Jun 22 19:36:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_crc xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_crc_wave.do}

view wave
view structure
view signals

do {tb_crc.udo}

run 1000ns
