######################################################################
#
# File name : tb_synch_fifo_wave.do
# Created on: Tue Apr 09 18:33:48 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
