######################################################################
#
# File name : tb_synch_fifo_compile.do
# Created on: Tue Apr 09 18:33:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../CRC.srcs/sources_1/new/sram.v" \
"../../../../CRC.srcs/sources_1/new/synch_fifo.v" \
"../../../../CRC.srcs/sim_1/new/tb_synch_fifo.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

